export const dataName = [
  { hr: '09:00', nameLottery: 'Anguilla'},
  { hr: '10:00', nameLottery: 'Anguilla'},
  { hr: '11:00', nameLottery: 'Anguilla'},
  { hr: '12:00', nameLottery: 'La Primera Día' },
  { hr: '12:05', nameLottery: 'Anguilla'},
  { hr: '12:30', nameLottery: 'La Suerte Dominicana' },
  { hr: '13:00', nameLottery: 'Real' },
  { hr: '13:55', nameLottery: 'LoteDom' },
  { hr: '14:30', nameLottery: 'Florida Tarde' },
  { hr: '14:30', nameLottery: 'Gana Más' },
  { hr: '15:00', nameLottery: 'Anguilla'},
  { hr: '15:30', nameLottery: 'New York Tarde' },
  { hr: '16:00', nameLottery: 'Anguilla'},
  { hr: '17:00', nameLottery: 'Anguilla'},
  { hr: '18:00', nameLottery: 'Anguilla'},
  { hr: '18:00', nameLottery: 'Nacional' },
  { hr: '18:00', nameLottery: 'La Suerte Dominicana' },
  { hr: '19:00', nameLottery: 'Anguilla'},
  { hr: '20:00', nameLottery: 'La Primera Noche' },
  { hr: '20:55', nameLottery: 'Loteka' },
  { hr: '20:55', nameLottery: 'Leidsa' },
  { hr: '22:00', nameLottery: 'Anguilla'},
  { hr: '22:45', nameLottery: 'Florida Noche' },
  { hr: '23:30', nameLottery: 'New York Noche' },
];